app_users/urls.py
from app_users import views
from django.urls import path

app_name = 'account'

urlpatterns = [
    path('switch_user/', views.user_logout, name='switch'),
    path('log_out/', views.user_logout, name='logout'),
    path('signup/', views.register, name='signup'),
    path('login/', views.user_login, name='login'),
]

mysiteTECHjs/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('principal.urls', namespace='main')),
    path('auth/', include('app_users.urls', namespace='app_user')),
]

# if settings.DEBUG:
#    urlpatterns += static.

principal/urls.py
from django.urls import path  # include
from rest_framework import routers
# from rest_framework.authtoken.views import obtain_auth_token

from .views import delete, search_results, generated, visiting  # listing_tasks_by_time, principal
from .api_views import AnnotationViewSet, TaskViewSet, ModelAnnotationListView, ModelUserListView
# _see_your_apis, _see_about_this_api, UserCreate, LoginView


router = routers.DefaultRouter()
router.register(r'task', TaskViewSet)
router.register(r'annotation', AnnotationViewSet)


app_name = 'main'
urlpatterns = [
    path('', generated, name='entry'),
    path('search/', search_results, name='search'),
    #path('search/user/', ModelUserListView.as_view(), name='model-user-list'),
    #path('search/note/', ModelAnnotationListView.as_view(), name='model-annotation-list'),
    path('<int:annotation_id>/', generated, name='change'),

    # path('api/', include(router.urls)),
    # path('login/', LoginView.as_view(), name='login'),
    # path('login/', obtain_auth_token, name='login'),
    # path('fullstack/', _see_your_apis, name='steward'),
    # path('signup/', UserCreate.as_view(), name='subscribe'),
    # path('fullstack/<int:annotation_id>/', _see_about_this_api, name='about_steward'),

    # path('journey/on<str:annotate_deadline_date>/', listing_tasks_by_time, name='on_this_day'),
    path('foreign/<int:user_id>/', visiting, name='visiting'),
    path('del/<int:annotation_id>/', delete, name='delete'),
]

principal/models.py
from django.contrib.auth.models import User
from django.db import models


class Annotation(models.Model):
    account = models.ForeignKey(User, null=True, blank=False, on_delete=models.SET_NULL)
    name = models.CharField(max_length=45)
    description = models.TextField()
    deadline = models.DateTimeField()  # format("YYYY-MM-DD\ HH:mn:sc")
    reminder = models.TimeField()  # format("HH:Mn:Sc")
    over = models.BooleanField(default=False)
    
    # viewers
    like = models.ManyToManyField(User, related_name='fan_zone',  blank=True, null=True)
    unlike = models.ManyToManyField(User, related_name='contests', blank=True, null=True)
    
    objects = models.Manager()

    def __str__(self) -> str:
        return f'{self.id}-----{self.name}-------{self.deadline.date()}'

    @staticmethod
    def get_nb_views(self) -> int:
        likers = Liker.objects.filter(action=True)
        dislikers = DisLiker.objects.filter(action=True)
        return len(likers)+len(dislikers)

    @staticmethod
    def get_nb_likes(self) -> int:
        likers = Liker.objects.filter(action=False)
        return len(likers)

    @staticmethod
    def get_nb_unlikes(self) -> int:
        dislikers = DisLiker.objects.filter(action=True)
        return len(dislikers)


class Task(models.Model):
    relation = models.ForeignKey(to=Annotation, on_delete=models.CASCADE)
    action = models.CharField(max_length=75)
    objects = models.Manager()


class Liker(models.Model):
    action = models.BooleanField(default=False)
    one = models.ForeignKey(User, on_delete = models.CASCADE)
    annotation = models.ForeignKey(Annotation, on_delete = models.CASCADE)


class DisLiker(models.Model):
    action = models.BooleanField(default=False)
    one = models.ForeignKey(User, on_delete = models.CASCADE)
    annotation = models.ForeignKey(Annotation, on_delete = models.CASCADE)


"""
    def regulator(self):
        if self.like:
            self.dislike != self.like
        else:
            self.like != self.dislike"""

principal/forms.py
from django import forms
from .models import Annotation


class AnnotationForm(forms.ModelForm):
    name = forms.CharField(
        required=True, widget=forms.TextInput(
            attrs={
                'class': "form-input", 'id': "firstname",
                'placeholder': "enter the title's"
            }
        )
    )
    description = forms.CharField(
        required=True, widget=forms.Textarea(
            attrs={
                'class': "form-input", 'id': "choose-file",
                'placeholder': "describe all steps you need to achieve",
                'rows': "4", 'cols': "50", 'style': "height:auto"
            }
        )
    )
    reminder = forms.TimeField(
        required=True, widget=forms.TimeInput(
            attrs={
                "type": "time",
                'id': "timing",
            }
        )
    )
    deadline = forms.DateTimeField(
        required=True, widget=forms.DateTimeInput(
            attrs={
                'type': "datetime-local",
                'id': "lastname",
                'class': "form-input",
                "placeholder": "enter the time over"
            }
        )
    )

    class Meta:
        model = Annotation
        fields = ['name', 'description', 'deadline', 'reminder']

principal/views.py
import datetime
from asgiref.sync import sync_to_async
#from django.http import JsonResponse

from .models import Annotation
from .forms import AnnotationForm

from app_users.forms import SignUpUserForm
from django.contrib.auth.models import User
from django.contrib.auth.views import login_required
from django.shortcuts import HttpResponseRedirect, reverse
from django.shortcuts import render  # , get_object_or_404, get_list_or_404

import openai
from openai.error import APIConnectionError


@sync_to_async()
@login_required(login_url='account:login')
def chatbot_response(user_input):
    response = openai.Completion.create(
        engine="text-davinci-003",
        prompt=user_input,
        temperature=0.5,
        max_tokens=1024,
        top_p=1,
        frequency_penalty=0,
        presence_penalty=0
    )
    return response["choices"][0]["text"]


@sync_to_async()
def visiting(request, user_id):
    u = User.objects.get(id=user_id)
    if request.method == 'POST':
        user_form = SignUpUserForm(data=request.POST, instance=u)
        if user_form.is_valid():
            user = user_form.save()
            user.save()
            login(request, user)
            return HttpResponseRedirect(reverse('main:entry'))
        else:
            print(user_form.errors)
    else:
        user_form = SignUpUserForm(instance=u)
    return render(
                request, 'app_users/sign_up.html',
                context={'user_form': user_form, 'action': "Change"}
            )


@sync_to_async()
def search_results(request):
    results = []
    target = request.GET['target']
    for a in Annotation.objects.filter(name__icontains=target):
        results.append(a)
    for u in User.objects.filter(email__icontains=target):
        results.append(u)
    for u in User.objects.filter(username__icontains=target):
        results.append(u)
    if len(results) and len(target):
        return render(request, 'principal/generat.html', {'res': results})
    return render(request, 'principal/generat.html')



@sync_to_async()
def generated(request, annotation_id=0):
    if request.user.username:
        nature: str = "Add"
        advice: str = "Getting connection to openai..."
        length: float = 0
        timing: str = ''
        qs = Annotation.objects.filter(account=request.user).order_by("deadline")
        for note in qs:
            coming_deadline = note.deadline
            delta = datetime.datetime(year=coming_deadline.year, month=coming_deadline.month,
                                      day=coming_deadline.day, hour=coming_deadline.hour,
                                      minute=coming_deadline.minute, second=coming_deadline.second, microsecond=0)
            if (delta - datetime.datetime.now()).total_seconds() < 0 and note.over is False:
                print(note)
                note.over = True
            elif (delta - datetime.datetime.now()).total_seconds() > 0 and note.over:
                note.over = False
            note.save()
        if request.method == 'POST':
            if annotation_id == 0:
                desc = request.POST['description']
                form = Annotation.objects.create(
                    account=request.user,
                    name=request.POST['name'],
                    deadline=request.POST['deadline'],
                    reminder=request.POST['reminder'], description=desc,
                    over=False
                )  # create
                deadline = datetime.datetime(year=int(request.POST['deadline'][0:3]),
                                             month=int(request.POST['deadline'][5:7]),
                                             day=int(request.POST['deadline'][8:10]),
                                             hour=int(request.POST['deadline'][11:13]),
                                             minute=int(request.POST['deadline'][14:16]),
                                             second=10, microsecond=10)
                if (deadline - datetime.datetime.now()).total_seconds() > 0:
                    over = False  # temps impartie finie
                else:
                    over = True

                form.over = over
                form.save()
                return HttpResponseRedirect(reverse('main:entry'))
            else:
                nature = 'change'
                note = Annotation.objects.get(id=annotation_id)
                form = AnnotationForm(request.POST, instance=note)
                if form.is_valid():
                    form.save()
                return HttpResponseRedirect(reverse('main:entry'))

        elif request.method == 'GET':
            if annotation_id == 0:
                form = AnnotationForm()  # create
            else:
                nature = 'change'
                note = Annotation.objects.get(id=annotation_id)
                try:
                    advice = chatbot_response(  # string regular expression
                            'I have a task named ' + note.name + r', that is described as this: ' + note.description +
                            r'. Can You help me to make it well done as quick as possible?'
                    )
                except APIConnectionError:
                    response = 'Oh! It seems that connection has temporarily stopped!'
                coming_deadline = note.deadline
                delta = datetime.datetime(year=coming_deadline.year, month=coming_deadline.month,
                                          day=coming_deadline.day, hour=coming_deadline.hour,
                                          minute=coming_deadline.minute, second=coming_deadline.second, microsecond=0)
                if delta > datetime.datetime.now():
                    timing = 'blue'  # restful

                    final = delta - datetime.datetime.now()
                else:
                    timing = 'red'  # late
                    final = datetime.datetime.now() - delta
                # 100% === 300px === 0s  // 0% === Opx === n_seconds  |
                length = abs(round(100 * 3 / (1 + (final.total_seconds() / 1000))))
                '''print('now it\'s', end=f'{datetime.datetime.now()}\n')'''
                form = AnnotationForm(instance=note)
            return render(request, template_name='principal/generat.html', context={  # 'principal/timer.html'
                "dj": qs,
                "form": form,
                "type": nature,
                "advice": advice,
                "length": length,
                "timing": timing,
            }
                          )
    elif request.user:  # new_User_or_Anonymous
        qs = User.objects.all()  # async filter(is_active=True, good_stat)

        """ matplotlib(user, login) """

        return render(request, template_name='./principal/generat.html', context={"dj": qs})


@sync_to_async
@login_required(login_url='account:login')
def listing_tasks_by_time(request, annotate_deadline_date):  # '%Y-%m-%d %H:%M:%S'
    """ http://localhost:3333/journey/on2023-05-19 18:32:24/ """
    annee = int(annotate_deadline_date[0:4])
    mois = str(annotate_deadline_date[5:7])
    if '-' in mois:
        mois = int(annotate_deadline_date[5])
    jour = str(annotate_deadline_date[7:10])
    print(jour)
    if '-' in jour:
        jour.replace('-', '')
    on_this_day = datetime.date(year=int(annee),
                                month=int(mois),
                                day=int(jour))
    qs = Annotation.objects.filter(over=True)
    right_qs = [item for item in qs if on_this_day == item.deadline.date()]
    return render(request, './principal/main.html', context={'dj': right_qs}, status=200)


@sync_to_async()
@login_required(login_url="account:login")
def delete(request, annotation_id):
    notif = Annotation.objects.get(id=annotation_id)
    if notif.account == request.user:  # only owner can delete his/her object
        notif.delete()
    return HttpResponseRedirect(reverse("main:entry"))

templates/principal/generat.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Landing Page</title>
    {% load static %}{% load i18n %}
    <link rel="stylesheet" href="{% static './styles/generat.css' %}">

    <script src="{% static './typed_scripts/calendar.js' %}" defer></script>
    <script src="{% static './typed_scripts/SearchBarAjax.js' %}" defer></script>

    <style>
        /* Additional styles for the message container */
        .message-container {
            display: flex;
            justify-content: center;
            align-items: center;
            height: 200px;
        }

        .message-text {
            font-size: 24px;
            font-weight: bold;
            color: #007bff;
            text-align: center;
        }
    </style>
    <script type="text/javascript" src="{% static './typed_scripts/timer.js' %}" defer></script>

</head>
<body>
    <header>
        <div class="header-container">
            <div class="logo">
                <img src="{% static 'img/icons8-todo-list-96.png' %}" alt="Website Logo" srcset="" height="">
            </div>
                <div class="countdown-el days-c">
                    <p class="big-text" id="days">0</p>
                    <span>days</span>
                </div>
                <div class="countdown-el hours-c">
                    <p class="big-text" id="hours">0</p>
                    <span>hours</span>
                </div>
                <div class="countdown-el mins-c">
                    <p class="big-text" id="mins">0</p>
                    <span>minutes</span>
                </div>
                <div class="countdown-el seconds-c">
                    <p class="big-text" id="seconds">0</p>
                    <span>seconds</span>
                </div>
            <div class="header-actions">
                <div class="search-bar">
                    <input type="text" placeholder="Search">
                    <button type="submit" id="searchButton">Search</button>
                </div>
                
                <div class="user-actions">
                    {% if request.user.username %}
                        <a href="{% url 'account:logout' %}">Logout</a>
                        <a href="{% url 'account:switch' %}">Switch</a>
                    {% else %}
                        <a href="{% url 'account:login' %}">Login</a>
                        <span>  </span>
                        <a href="{% url 'account:signup' %}">Sign Up</a>
                    {% endif %}
                </div>
            </div>
        </div>
    </header>


    <div class="sidebar-container">
        <div class="sidebar">
            <ul>
                <li><a href="{% url 'main:entry' %}">Home</a></li>
                <li>
            <a href="https://www.figma.com/file/jLgnEkiBEheIyOvIaKygq5/My_own-and_personalised_portfolio?node-id=3%3A4&t=creaxtc4EKSFBXF0-1">
                Author
            </a>
                </li>
            {% if request.user.username %}
                <li><a href="{% url 'main:visiting' request.user.id %}">About me</a></li>
            {% endif %}
                <li><a href="#sponsorship">Services</a></li>
                <li><a href="#sponsorship">Contact</a></li>
                <li><a href="#">Settings</a></li>
            </ul>
        </div>

        <main>

            <div class="logo">
                    <!--  -->
            </div>
            {% if request.user.username %}
                {% for i in dj %}
                    {% if not i.is_even %}
                        <div class="card blue">
                            <a href="{% url 'main:change' i.id %}">
                                <div class="card-header">
                                    <h3> {{ i.name }} </h3>
                                    {% if i.over %}
                                        Over since {{ i.deadline.date| date:"d M Y" }}
                                    {% else %}
                                        {% block clock %}{% endblock %}
                                    {% endif %}
                                </div>
                                <p class="not-visible">{{ i.deadline }}</p>
                                <div class="card-body">
                                    <p>
                                        {{ i.description }}
                                    </p>
                                </div>
                            </a>
                            ---------------------------<a style="color:white" href="{% url 'main:delete' i.id %}">delete</a>-------------------------
                        </div>

                    {% else %}
                        <div class="card white">
                            <div class="card-header">
                                <div class="countdown">05:30:00</div>
                            </div>
                            <div class="card-body">
                                <h3>Title 2</h3>
                                <p>Description text 2</p>
                            </div>
                        </div>
                    {% endif %}
                {% endfor %}
            {% endif %}
            {% if not request.user.is_authenticated %}
            <div class="message-container">
                <p class="message-text">You have to log in or sign up first.</p>
            </div>
            {% else %}
            <div class="form-container">
                <form action="" enctype="application/x-www-form-urlencoded" method="post" class="signup-form">
                    <!-- form header -->
                        {% csrf_token %}
                    <div class="form-header">
                        <h1>New Notation for {{ user.username }}</h1>
                        {{ form.account }}
                    </div>

                    <!-- form body -->
                    <div class="form-body">
                            {{form.errors}}
                        {% if form.errors %}
                            <p>Please correct the following errors:</p>
                            {% for field in form %}
                                {% if field.errors %}
                                    <div>{{ field.label }}: {{ field.errors|striptags }}</div>
                        {% endif %}
                            {% endfor %}
                        {% endif %}
                        <div class="horizontal-group">
                            <div class="form-group left">
                                <label for="firstname" class="label-title">Title</label>
                                {{ form.name }}
                            </div>
                            <div class="form-group right">
                                <label for="lastname" class="label-title">Deadline</label>
                                {{ form.deadline }}
                            </div>
                        </div>
                        <div class="form-group">
                            <label for="timing" class="label-title">Reminder</label>
                            {{ form.reminder }}
                        </div>
                        <!-- Bio -->
                        <div class="form-group">
                            <label for="choose-file" class="label-title">Bio</label>
                            {{ form.description }}
                        </div>
                    </div>
                    <!-- form footer -->
                    <div class="form-footer">
                        {% if type == 'change' %}
                            <button type="reset">Undo</button>
                        {% endif %}
                        <button type="submit">{{ type }}</button>
                    </div>
                </form>
            </div>
            {% endif %}
        </main>

        
    </div>

    <footer>
        <div id="sponsorship">
            <div id="DJ" ><a href="https://Django.org/"><img src="{% static 'img/icons8-django-a-high-level-python-web-framework-that-encourages-rapid-development-48.png' %}" alt="Django" srcset=""></a></div>
            <div id="OpenAI" ><a href="https://openai.com/"><img src="{% static 'img/icons8-chatgpt-96.png' %}" alt="OpenAI" srcset=""></a></div>
            <div id="python3" ><a href="https://python.org/"><img src="{% static 'img/icons8-python-48.png' %}" alt="Python" srcset=""></a></div>
            <div id="CodeOSS" ><a href="https://vscode.org/"><img src="{% static 'img/icons8-visual-studio-code-2019-96.png' %}" alt="VSCODE" srcset=""></a></div>
            <div id="XfceSession" ><a href="https://xubuntu.org/"><img src="{% static 'img/icons8-ubuntu-logo-96.png' %}" alt="Xubuntu" srcset=""></a></div>
            <div id="Pycharm" ><a href="https://jetbrains.com/Pycharm/"><img src="{% static 'img/icons8-jetbrains-logo-96.png' %}" alt="JetBrains" srcset=""></a></div>
            <div id="github" ><a href="https://github.com/TahianSylvain/TECHjs/"><img src="{% static 'img//icons8-github-50.png' %}" alt="Git" srcset=""></a></div>
        </div>

        <p style="">
            If something wrong happened, Don't hesitate to <a href="mailto:ranjalahyandrytahianasylvain@gmail.com">mail me</a>
        </p>
        <p>
            But if you are amazed by it! Make me a star at <a href="https://github.com/TahianSylvain/TECHjs/">my GitHub repos</a>
        </p>

        <ul>
            <li><a href="#">Privacy Policy</a></li>
            <li><a href="#">Terms of Service</a></li>
            <li><a href="#">FAQ</a></li>
        </ul>
    </footer>
    <!-- <script src="{% static './typed-scripts/generatBody.js' %} "></script> -->
</body>
</html>

templates/principal/userProfile.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    {% load static %}
    <link rel="stylesheet" href="{% static 'styles/generat.css' %}">
    <title> {{ u.username }} </title>
    <style>
        /* Additional styles for the message container */
          .message-container {
            display: ;
            justify-content: center;
            align-items: center;
            height: 200px;
          }

          .message-text {
            font-size: 24px;
            font-weight: bold;
            color: #007bff;
            text-align: center;
          }
    </style>
</head>
<body>
    <header>
        <div class="header-container">
            <div class="logo">
                <img src="{% static 'img/icons8-todo-list-96.png' %}" alt="Website Logo" srcset="" height="">
            </div>

            <div class="header-actions">
                <div class="search-bar">
                    <input type="text" placeholder="Search">
                    <button type="submit" id="searchButton">Search</button>
                </div>

                <div class="user-actions">
                    {% if request.user.username %}
                        <a href="{% url 'account:logout' %}">Logout</a>
                        <a href="{% url 'account:switch' %}">Switch</a>
                    {% else %}
                        <a href="{% url 'account:login' %}">Login</a>
                        <span>  </span>
                        <a href="{% url 'account:signup' %}">Sign Up</a>
                    {% endif %}
                </div>
            </div>
        </div>
    </header>

    <div class="sidebar-container">
        <div class="sidebar">
            <ul>
                <li><a href="{% url 'main:entry' %}">Home</a></li>
                <li>
            <a href="https://www.figma.com/file/jLgnEkiBEheIyOvIaKygq5/My_own-and_personalised_portfolio?node-id=3%3A4&t=creaxtc4EKSFBXF0-1">
                Author
            </a>
                </li>
                <li><a href="#">About me</a></li>
                <li><a href="#sponsorship">Services</a></li>
                <li><a href="#sponsorship">Contact</a></li>
                <li><a href="#">Settings</a></li>
            </ul>
        </div>

        <main>
            <h1>{{ u }}</h1>
                {% for a in annotate %}
                    <div>
                        <h3> {{ a.name }} </h3> <i>{{ a.deadline }}<i/>
                        <p>{{ a.description }}<p/>

                        {% if user.username %}   {# can like #}
                            <form action="" method="post">
                                {% csrf_token %}
                                <button type="submit">Like</button>
                            </form>
                                    {# liked or disliked #}
                            <form action="" method="post">
                                {% csrf_token %}
                                <button type="submit">Dislike</button>
                            </form>
                        {# else view only #} {% endif %}
                    </div>
                {% endfor %}

        </main>
    </div>

    <footer>
        <div id="sponsorship">
            <div id="DJ" ><a href="https://Django.org/"><img src="{% static 'img/icons8-django-a-high-level-python-web-framework-that-encourages-rapid-development-48.png' %}" alt="Django" srcset=""></a></div>
            <div id="OpenAI" ><a href="https://openai.com/"><img src="{% static 'img/icons8-chatgpt-96.png' %}" alt="OpenAI" srcset=""></a></div>
            <div id="python3" ><a href="https://python.org/"><img src="{% static 'img/icons8-python-48.png' %}" alt="Python" srcset=""></a></div>
            <div id="CodeOSS" ><a href="https://vscode.org/"><img src="{% static 'img/icons8-visual-studio-code-2019-96.png' %}" alt="VSCODE" srcset=""></a></div>
            <div id="XfceSession" ><a href="https://xubuntu.org/"><img src="{% static 'img/icons8-ubuntu-logo-96.png' %}" alt="Xubuntu" srcset=""></a></div>
            <div id="Pycharm" ><a href="https://jetbrains.com/Pycharm/"><img src="{% static 'img/icons8-jetbrains-logo-96.png' %}" alt="JetBrains" srcset=""></a></div>
            <div id="github" ><a href="https://github.com/TahianSylvain/TECHjs/"><img src="{% static 'img//icons8-github-50.png' %}" alt="Git" srcset=""></a></div>
        </div>

        <p style="">
            If something wrong happened, Don't hesitate to <a href="mailto:ranjalahyandrytahianasylvain@gmail.com">mail me</a>
        </p>
        <p>
            But if you are amazed by it! Make me a star at <a href="https://github.com/TahianSylvain/TECHjs/">my GitHub repos</a>
        </p>

        <ul>
            <li><a href="#">Privacy Policy</a></li>
            <li><a href="#">Terms of Service</a></li>
            <li><a href="#">FAQ</a></li>
        </ul>
    </footer>
</body>
</html>